<?php

namespace AppBundle\Repository;

/**
 * templateChampRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class templateChampRepository extends \Doctrine\ORM\EntityRepository
{
}
