# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            logout_on_user_change: true
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: /login
                csrf_token_generator: security.csrf.token_manager
                success_handler: redirect.after.login
 
            oauth:
                failure_path: /login
                login_path: /login
                check_path: /connect_check
                provider: fos_userbundle
                resource_owners:
                    facebook: "/login/check-facebook"
                    google: "/login/check-google"
                oauth_user_provider:
                    service: app.provider.oauth
            logout:       true
            anonymous:    true
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/users/, role: ROLE_USER }
        - { path: ^/champ/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/cv/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/section/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/groupe/, role: IS_AUTHENTICATED_FULLY }
     
    access_denied_url: /login